services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=dushyant
      - POSTGRES_PASSWORD=dushyant
      - POSTGRES_DB=ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - "./ny_taxi_db:/var/lib/postgresql/data:rw"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
